#! /bin/sh

# get the Run ID
echo "What's the two letter Run ID (***lowercase***)?"
read runID
runID=`echo $runID | tr [A-Z] [a-z]`
echo ''

# get four digit year
echo "What's the four-digit year?"
read year
echo ''

# get two digit month
echo "What's the two-digit month?"
read month
echo ''

# get two digit day
echo "What's the two-digit starting day (in local time)?"
read day
echo ''

# get Alex's Data Repository password
echo "What's Alex's Lick Remote Data Repository password (the characters will NOT show up below)?"
stty -echo
read password
stty echo
echo ''
echo ''

# other variables
kastDir=/o/ishivvers/kastreductions
toolsDir=/o/ishivvers/kastreductions/silverclubb/tools

# make new data directory
mkdir -p $kastDir/reductions/$runID/rawdata

# get into the new directory
cd $kastDir/reductions/$runID/rawdata

# wget the big data tarball
wget --no-check-certificate --http-user="Alex Filippenko" --http-passwd="$password" -O alldata.tar.gz "https://mthamilton.ucolick.org/data/$year-$month/$day/shane/?tarball=true&allfiles=true"

# unzip data
gunzip -f alldata.tar.gz

# untar data
tar -xvf alldata.tar

# move data from default data directory to current directory
\mv d*/* .

# remove the now empty data directory
\rmdir d*

# remove unzipped data file
\rm alldata.tar

# change permissions so that the owner can write over the files
chmod u+w *fits

## remove the DATASEC keyword from the FITS header of the red side observations
#/Applications/itt/idl/idl81/bin/idl << EOF
#.rnew /Users/Kelsey/observing/kast/tools/rmdatasec.pro
#rmdatasec
#retall
#exit
#EOF

echo ''
# create e-log and put it into the rawdata folder
python $toolsDir/wiki2elog.py
echo ''

# make copy of rawdata directory                                                    
# cp -r $kastDir/reductions/$runID/rawdata $kastDir/reductions/$runID/rawdatacopy

# move back up into run folder
cd $kastDir/reductions/$runID

echo ''
echo '  Program is finished. The Kast raw data should now be on your computer.'
echo ''
